workspace 'MyiOSExploration'
project 'Masonry实践/Masonry实践.xcodeproj'

use_frameworks!
target :Masonry实践 do
platform :ios, '8.0'
pod 'Masonry'
pod 'MJExtension'
pod 'SDWebImage'
project 'Masonry实践/Masonry实践.xcodeproj'
end

use_frameworks!
target :'ReactiveCocoa & MVVM' do
    platform :ios, '8.0'
    pod 'ReactiveCocoa'
    project 'ReactiveCocoa & MVVM/ReactiveCocoa & MVVM.xcodeproj'
end

use_frameworks!
target :'Quartz 2D实践' do
    platform :ios, '8.0'
#    pod 'Masonry'
    project 'Quartz 2D实践/Quartz 2D实践.xcodeproj'
end
